//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRestApi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class student
    {
        public int RegNo { get; set; }
        [Required (ErrorMessage = "please enter a name")]
        public string StudentName { get; set; }
        [Required (ErrorMessage = "please select Subjects")]
        public Nullable<int> SubjectId { get; set; }
    
        public virtual subject subject { get; set; }
    }
}
