//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRestApi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class subject
    {
        public subject()
        {
            this.students = new HashSet<student>();
        }
    
        public int SubjectId { get; set; }
        [Required (ErrorMessage = "please provide a subjects")]
        public string Subjects { get; set; }
    
        public virtual ICollection<student> students { get; set; }
    }
}
